os: Visual Studio 2022

init:
  - ps: $Env:DOTNET_CLI_TELEMETRY_OPTOUT=1
  - ps: $Env:DOTNET_NOLOGO=1

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: +++VALUE # FROM https://coveralls.io/repos/new ENCRYPT WITH https://ci.appveyor.com/tools/encrypt

cache:
  - '%LocalAppData%\NuGet\Cache -> **\+++PROJECT.*.csproj'
  - '%LocalAppData%\NuGet\v3-cache  -> **\+++PROJECT.*.csproj'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%UserProfile%\.dotnet\tools -> appveyor.yml'

install:
  - ps: ./scripts/tooling.ps1

configuration:
  - Debug

dotnet_csproj:
  patch: true
  file: 'src\**\+++PROJECT.*.csproj'
  version_suffix: "{branch}-{build}"

before_build:
  - dotnet restore -verbosity:q

build:
  parallel: true
  verbosity: quiet

after_build:
  - ps: dotnet pack --no-restore --no-build -verbosity:q --configuration $Env:CONFIGURATION

test_script:
  - ps: ./scripts/test.ps1

artifacts:
  - path: 'src\**\+++PROJECT.*.nupkg'

deploy:
  - provider: NuGet # Nuget.org
    api_key:
      secure: +++VALUE # FROM https://www.nuget.org/account/apikeys ENCRYPT WITH https://ci.appveyor.com/tools/encrypt
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: /^release/
  - provider: NuGet # Github packages
    server: https://nuget.pkg.github.com/+++YOUindex.json
    artifact: /.*\.nupkg/
    draft: true
    username: ProphetLamb
    api_key:
      secure: +++VALUE # FROM https://github.com/settings/tokens ENCRYPT WITH https://ci.appveyor.com/tools/encrypt
    on:
      branch: /^release/

for:
  - branches:
      only:
        - /^release/

    configuration:
      - Release
