os: Visual Studio 2022

init:
  - ps: $Env:DOTNET_CLI_TELEMETRY_OPTOUT=1
  - ps: $Env:DOTNET_NOLOGO=1

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: 6idZ+wESP48CKKFLSy6uLzGloNEwsL54y1TcVbPR75NFAgOgo1XBUtFYh2oG3TmR

cache:
  - '%LocalAppData%\NuGet\Cache -> **\LoggerMessage.*.csproj'
  - '%LocalAppData%\NuGet\v3-cache  -> **\LoggerMessage.*.csproj'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%UserProfile%\.dotnet\tools -> appveyor.yml'

install:
  - ps: ./scripts/tooling.ps1

configuration:
  - Debug

dotnet_csproj:
  patch: true
  file: 'src\**\LoggerMessage.*.csproj'
  version_suffix: "{branch}-{build}"

before_build:
  - dotnet restore -verbosity:q

build:
  parallel: true
  verbosity: quiet

after_build:
  - ps: dotnet pack --no-restore --no-build -verbosity:q --configuration $Env:CONFIGURATION

test_script:
  - ps: ./scripts/test.ps1

artifacts:
  - path: 'src\**\LoggerMessage.*.nupkg'

deploy:
  - provider: NuGet # Nuget.org
    api_key:
      secure: TSNUcxYNb9x2fwwxYxZByKKvrF86dfNF7lQQRqNmoq1q+y7kteHc2nbLCXk+RIpB
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: /^release/
  - provider: NuGet # Github packages
    server: https://nuget.pkg.github.com/ProphetLambindex.json
    artifact: /.*\.nupkg/
    draft: true
    username: ProphetLamb
    api_key:
      secure: C8xC+nv4MSirvCA8kUoan4sz2B8aFaytWW2m4lrLqXhAnSkOmo6fN90QHiGJoSGI
    on:
      branch: /^release/

for:
  - branches:
      only:
        - /^release/

    configuration:
      - Release
